### ISSUE TITLE
Cannot reference the package in .NET8 project

### ISSUE THREAD

**Issue by leon238** [Redth/Maui.ContentButton#7]
I tried to reference your Plugin.Maui.ContentButton nuget package in my MAUI .NET8 project and it does not work as your package does not support .NET8 projects (non platform specific). Can you advise how to use it? Thank you.

![maui-content-button-error](https://github.com/user-attachments/assets/9b7e33ef-3ed5-4bb8-83df-9056fcbfcd2c)

**Comment by Redth** [comment]
What's your goal with referencing it here? How are you planning to use the "API" for it?

Given it's a Control abstraction, it's likely not very useful to have in a plain `net8.0` project.  If you're just trying to install the plugin to a project that happens to have a net8.0 TFM, you can conditionally include the nuget packagereference.

**Comment by zachdean** [comment]
@Redth we also ran into the same issue. How we use the net8.0 TFM is so that we can reference our MAUI app in a test project. We have also been going down the road have constructing controls and testing them inside of a net8.0 test project. This [pr](https://github.com/Redth/Maui.ContentButton/pull/10) would add the TFM allow the package to be targeted in net8.0, we cannot exclude the package for net8.0 since that is going to break any xaml that is referencing the ContentButton.
